### ISSUE TITLE
Diacritics support

### ISSUE THREAD

**Issue by Martindob** [JavaFactoryDev/PunishControl-Wiki#11]
Could you add diacritics support?

**Comment by EsGibtKeineMitte** [comment]
Could you please provide more information on what you mean with diacritics support.

**Comment by Martindob** [comment]
@EsGibtKeineMitte Strange characters are displayed when I put something in the config by diacritics, eg when I change the prefix

**Comment by JavaFactoryDev** [comment]
Could you please upload your plugins/PunishControl folder to show us where this exactly happens?

**Comment by Martindob** [comment]
I had to erase folder data, there is no problem, the problem is in PunishControl



[PunishControl.zip](https://github.com/JavaFactoryDev/PunishControl-Wiki/files/3804343/PunishControl.zip)

**Comment by JavaFactoryDev** [comment]
We hope to fix this in future updates but it is normal that diacritics get replaced to CharCodes when the YAML is reloaded; what usually only happens when keys are missing init.

**Comment by Martindob** [comment]
Just not, the diacritics is confused with some characters, I have a test server on the PC, so it is in a language localization as a PC, so when I run the plugin, I have strange characters everywhere, even if I did not translate anything.

**Comment by JavaFactoryDev** [comment]
The bug is fixed in a development version of PunishControl. We will fix this with a more modular TranslationSystem

**Comment by JavaFactoryDev** [comment]
Added with latest version
