### ISSUE TITLE
1.12.2: Massive bug on punish control

### ISSUE THREAD

**Issue by daniiieru** [JavaFactoryDev/PunishControl-Wiki#12]
i downloaded the lastest update of the plugin punish control so i put on my proxy and when i join the server it does this : https://pastebin.com/4G5RpKRZ and when i do /pc it shows this error on my proxy console : https://pastebin.com/kPXB66fU
[PunishControl.zip](https://github.com/JavaFactoryDev/PunishControl-Wiki/files/4252260/PunishControl.zip)
And also when i use a item of my hotbar, all my items in my hotbar disappears until i open the inventory and click on the hotbar for the items to reappear :/

**Comment by daanh432** [comment]
@daniiieru I think you are using the pre release version [1.3](https://github.com/JavaFactoryDev/PunishControl-Wiki/releases/tag/1.3)

Could you try using the latest stable release [1.2.5](https://github.com/JavaFactoryDev/PunishControl-Wiki/releases/tag/1.2.5) and see if that works fine?

**Comment by JavaFactoryDev** [comment]
okay will be fixed until next release, also this is only a „cosmetic“ issue.
