### ISSUE TITLE
Suggestion: Timezones

### ISSUE THREAD

**Issue by larssieboy18** [JavaFactoryDev/PunishControl-Wiki#6]
Hello,

Errors are all fixed. Now I'm here with a suggestion :) I would really like it to be able to add timezones and/or use server time. Bans now show a time that is 2 hours behind my server time, which is really confusing. Is it possible to add timezones in the config?

Best regards,
Lars

**Comment by JavaFactoryDev** [comment]
Will be added in 1.0.6

**Comment by JavaFactoryDev** [comment]
So we added this feature in the newest version:
You can add a time shift in hours in the PunishControl.yml.
But please keep in mind that this mostly has something to do with the time zone of your server.
You could use /phc export to update your PunishControl.yml

Greetings,
Leonhard.
