### ISSUE TITLE
Suggestion: warn command

### ISSUE THREAD

**Issue by larssieboy18** [JavaFactoryDev/PunishControl-Wiki#7]
Hi,

Another suggestion: make it so that punish control can give warnings. For example, a minor offence would result in a warning for the player.
If it's possible, I would really like it if a number of warnings in an X period of time automagically result in a mute/ban. 

Best regards,
Lars

**Comment by JavaFactoryDev** [comment]
Added in the newest version. Thanks for your enhancement:).

Greetings,
Leonhard
