### ISSUE TITLE
Insufficient Perms

### ISSUE THREAD

**Issue by zoxford** [JavaFactoryDev/PunishControl-Wiki#8]
I added the perms to my owner rank and im get Insufficient permissions to the command. @JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Hey!
Thanks for using PunishControl!
We need more information to know whether this is an issue or just to know whats going on.

Which permission have you added to your Account? (PunishControl.*) is the right permission to get full access. 

Which PermissionPlugin are you using? 
Maybe you are using a Bukkit (non-BungeeCord) Permissions-Plugin so BungeeCord can't know that you have this permission.

For all functions please see the [Wiki](https://github.com/JavaFactoryDev/PunishControl-Wiki/wiki/Permissions)

**Comment by EsGibtKeineMitte** [comment]
If no futher information given, this issue will be closed.
